import os
import json
import requests
import re
import base64
from functools import lru_cache
from io import BytesIO
from typing import List, Optional, Dict, Any

from fastapi import FastAPI, UploadFile, File, Form, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from pydantic_settings import BaseSettings
from PIL import Image
import google.generativeai as genai

# --- Initialize FastAPI (single instance) ---
app = FastAPI(title="SnapStyle API")

# --- Add CORS Middleware BEFORE routes ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "https://1507cc3e-8646-4587-bcef-865fd8c99e37.lovableproject.com",
        "http://localhost:5173",
        "*"  # note: "*" is permissive; remove if you want strict origins
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- 1. Settings Management (Replaces st.secrets) ---
class Settings(BaseSettings):
    GOOGLE_API_KEY: str
    CSE_ID: str

    class Config:
        env_file = ".env"

@lru_cache()
def get_settings():
    return Settings()

# --- 2. Configure Google API Key at Startup ---
try:
    settings = get_settings()
    # Only configure if key exists
    if getattr(settings, "GOOGLE_API_KEY", None):
        genai.configure(api_key=settings.GOOGLE_API_KEY)
except Exception as e:
    print(f"Warning: Could not load .env file or configure Google API. Error: {e}")

# --- 4. Refactored Core Functions ---

def image_generation(image_bytes: bytes, style: str) -> (bytes, dict):
    """
    Generates a new fashion image and description from image bytes.

    Args:
        image_bytes: The image file as bytes.
        style: Style type (e.g., modern, casual).
    
    Returns:
        A tuple of (image_output_bytes, description_json)
    """
    # Use a triple-quoted f-string and double braces for literal JSON example braces
    prompt = f"""**Task**: Generate a new fashion image based on the person in the provided image, PLUS a JSON text description of the new outfit.
**Style**: {style}

**Instructions for Generation**:
1.  **Image Analysis**: First, carefully analyze the provided image...
2.  **Outfit Design**: Based on your analysis, design a complete outfit...
3.  **Text Description**: Provide a detailed, search-friendly JSON description...

**Required Description Format (JSON)**:
Respond ONLY with a JSON object. Example:
```json
{{
  "Shirt": "Men's light wash denim button-up shirt",
  "Bottoms": "Men's slim-fit olive green chino pants"
}}
```"""

    try:
        # Open image from bytes
        image = Image.open(BytesIO(image_bytes))

        # Initialize model (ensure you have the correct model name & client usage)
        model = genai.GenerativeModel('gemini-2.0-flash-exp')
        # NOTE: model.generate_content signature / usage might differ depending on the SDK version.
        # The following assumes the SDK accepts a list with prompt and inline image. Update if needed.
        response = model.generate_content([prompt, image])

        generated_image_pil = None
        description_raw_text = ""

        # Extract text and image from response
        for part in response.candidates[0].content.parts:
            if hasattr(part, 'text') and part.text:
                description_raw_text += part.text
            elif hasattr(part, 'inline_data') and part.inline_data:
                # inline_data.data is assumed to be bytes of an image
                generated_image_pil = Image.open(BytesIO(part.inline_data.data))

        description_json = {}
        if description_raw_text:
            try:
                json_match = re.search(r"```json\n(.*?)```", description_raw_text, re.DOTALL)
                if json_match:
                    json_string = json_match.group(1).strip()
                else:
                    json_string = description_raw_text.strip()
                description_json = json.loads(json_string)
            except json.JSONDecodeError:
                print(f"Failed to decode JSON from: {description_raw_text}")
                description_json = {"error": "Failed to parse description JSON"}

        if generated_image_pil:
            # Convert PIL image to bytes for API response
            img_buffer = BytesIO()
            generated_image_pil.save(img_buffer, format="PNG")
            image_output_bytes = img_buffer.getvalue()
            return image_output_bytes, description_json
        else:
            raise HTTPException(status_code=500, detail="No image was generated by the model.")

    except Exception as e:
        print(f"Error in image_generation: {e}")
        raise HTTPException(status_code=500, detail=f"Image generation failed: {e}")


def google_product_search(query: str, api_key: str, cse_id: str, num: int = 5) -> List[Dict[str, Any]]:
    """Search products and get titles, links, snippets, and images."""
    url = "https://www.googleapis.com/customsearch/v1"
    params = {
        "q": query,
        "key": api_key,
        "cx": cse_id,
        "num": num,
        # If you want images only, use "searchType": "image", otherwise remove
        "searchType": "image"
    }

    try:
        response = requests.get(url, params=params)
        response.raise_for_status()
        data = response.json()

        results = []
        for item in data.get("items", []):
            results.append({
                "title": item.get("title"),
                "link": (item.get("image") or {}).get("contextLink") or item.get("link"),
                "image_url": item.get("link"),
                "thumbnail_url": (item.get("image") or {}).get("thumbnailLink")
            })
        return results
    except requests.RequestException as e:
        print(f"Error in google_product_search: {e}")
        raise HTTPException(status_code=500, detail=f"Google Search API request failed: {e}")


# --- 5. API Response Models (Pydantic) ---
class GenerationResponse(BaseModel):
    description: dict
    image_base64: str

class SearchItem(BaseModel):
    title: Optional[str]
    link: Optional[str]
    image_url: Optional[str]
    thumbnail_url: Optional[str]

class SearchResponse(BaseModel):
    results: List[SearchItem]


# --- 6. API Endpoints ---

@app.post("/generate-fashion", response_model=GenerationResponse)
async def create_fashion_image(
    style: str = Form(..., description="The fashion style, e.g., 'casual', 'modern'"),
    file: UploadFile = File(..., description="The user's input image (PNG or JPG)")
):
    """
    Generates a new fashion image and outfit description.
    """
    if file.content_type not in ["image/png", "image/jpeg"]:
        raise HTTPException(status_code=400, detail="Invalid file type. Please upload PNG or JPG.")

    image_bytes = await file.read()
    generated_image_bytes, description_json = image_generation(image_bytes, style)
    image_base64_string = base64.b64encode(generated_image_bytes).decode('utf-8')

    return GenerationResponse(
        description=description_json,
        image_base64=image_base64_string
    )


@app.get("/search-products", response_model=SearchResponse)
async def search_for_products(
    query: str,
    setti
